### ISSUE TITLE
"No transports available"

### ISSUE THREAD

**Issue by stephenplusplus** [sjmueller/firebase-react-native#1]
Thanks for putting this repo together! I'm trying to use the set-up here, but run into:

![screen shot 2015-05-08 at 4 03 54 pm](https://cloud.githubusercontent.com/assets/723048/7544529/e23a0c28-f59b-11e4-924a-051ccd84e92d.png)

Is this a sign of me doing something wrong, or maybe you've run into this and know how to handle it?

Thanks!

**Comment by stephenplusplus** [comment]
More details, this is while trying to authenticate a user from a Facebook access token.

I stumbled across this: http://stackoverflow.com/questions/26541571/error-creating-user-error-there-are-no-login-transports-available-for-the-r

I previously used the badfortrains fork of react native with his firebase-debug and didn't run into the error: https://github.com/badfortrains/wsExample

However, using his firebase-debug with the react-native fork you recommend in the readme doesn't work.

I am sadly very inexperienced with Web Sockets, so forgive me if this is not an intelligent guess, but could there be multiple ways of connecting to a socket, and this one doesn't work for this?

**Comment by stephenplusplus** [comment]
After pressing a bunch of keys and going through the readme steps again, I activated magic, and it worked! If anyone else runs into something weird like this, let me know, and we can trade files.

Sorry for the noise!

**Comment by olivierlesnicki** [comment]
Having the same issue @stephenplusplus

**Comment by jakeoverall** [comment]
@stephenplusplus  I am having this same issue when updating my project from firebase-debug and badfortrains/react-native. 

Also what do you mean by 
  "I activated magic"

Thanks in advanced
