### ISSUE TITLE
RN now has WebSocket Polyfill merged

### ISSUE THREAD

**Issue by lazywei** [sjmueller/firebase-react-native#2]
Hi,

ReactNative now has merged the WebSocket Polyfill. I'm wondering do we need to change anything in this package to make it work?

**Comment by sjmueller** [comment]
Hey there @lazywei. As of v2.2.7, firebase now has great support for react-native.  Works pretty well, so I'm deprecating this lib.

**Comment by lazywei** [comment]
Got it. Thanks for informing.

/cc @gagedark



-- Chih-Wei (Bert)
